# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
  - stage: test_report
    displayName: test report
    jobs:
      - job: test_report
        pool:
          vmImage: "windows-2019"
        container:
          image: vladimirak/terraformcr:58
          endpoint: docker hub

        steps:
          - script: C:\UiPath\UiPath.Studio.CommandLine.exe analyze -p $(Build.SourcesDirectory)\project.json > $(Build.ArtifactStagingDirectory)\report.json
            displayName: "Build the artifact report"
          - publish: $(Build.ArtifactStagingDirectory)
            artifact: analysis
            
  - stage: publish_package
    displayName: publish package
    jobs:
      - job: publish_package
        pool:
          vmImage: "windows-2019"
        container:
          image: vladimirak/terraformcr:58
          endpoint: docker hub

        steps:
          - script: C:\UiPath\UiRobot.exe pack $(Build.SourcesDirectory)\project.json -o $(Build.ArtifactStagingDirectory)\ -v 1.0.$(Build.BuildNumber)
            displayName: "Build the artifact package"
          - publish: $(Build.ArtifactStagingDirectory)
            artifact: drop
